### ISSUE TITLE
idea for improving branding of echarty

### ISSUE THREAD

**Issue by lgnbhl** [helgasoft/echarty#16]
Hi,
It could be interesting to make a comparison with other R package wrapping "Echarts", in particular the popular R package "echarts4r". 

- What are the key differences between "echarty" and "echarts4r"?
- Is "echarty" lighter/faster than "echarts4r"? (give a proof of it with R code)
- how the API differs between "echarty" and "echarts4r"?
- What are the main advantages using "echarty" and not "echarts4r"?

This would help new users to choose echarty for their projets instead of echarts4r.

Thanks again for you help regarding https://github.com/helgasoft/echarty/issues/14.

Best,
Felix

**Comment by helgasoft** [comment]
Yes, agree, it is time to build a comparison table. Here is the essence. 
The **API** is completely different. While _echarts4r_ is wrapping many [ECharts options](https://echarts.apache.org/en/option.html) in separate commands, _echarty_ relies exclusively on R lists to match ECharts options. This adds flexibility (we think) and make for smaller code size - _echarty_ [176KB](https://img.shields.io/github/languages/code-size/helgasoft/echarty) vs _echarts4r_ [877KB](https://img.shields.io/github/languages/code-size/JohnCoene/echarts4R).  
Less commands to learn is a benefit - _echarty_ has only two(2) major commands to build any chart: **_ec.init_** and **_ec.upd_**. Actually we encourage users to work primarily with the [original ECharts documentation](https://echarts.apache.org/en/option.html) because all options can be plugged directly in _echarty_ commands as R-lists.

Your test case #14 is an example of **functionality scope**.
``` ... categories= LETTERS[1:4], dimension= 2 ...``` 
_echarty_ covers [ECharts dataset](https://echarts.apache.org/en/option.html#dataset), but _echarts4r_ does not. That's why _categories_ and _dimension_ options work in _echarty_.

**Comment by helgasoft** [comment]
added a **comparison table** in the Github main page introduction
